config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts
  get 'home/index'

  get 'tracks/getcoordinates/:id', to: "tracks#getcoordinates"

  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :latitude_from, :length => { :minimum => 3}, format: { with: /[0-9]{1,2}.[0-9]+/, message: "Only format similar is: 11.22222" }
  validates :longtitude_from, :length => { :minimum => 3}, format: { with: /[0-9]{1,2}.[0-9]+/, message: "Only format similar is: 11.22222" }
  validates :latitude_to, :length => { :minimum => 3}, format: { with: /[0-9]{1,2}.[0-9]+/, message: "Only format similar is: 11.22222" }
  validates :longtitude_to, :length => { :minimum => 3}, format: { with: /[0-9]{1,2}.[0-9]+/, message: "Only format similar is: 11.22222" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to tracks_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :publishdate)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track, only: [:show, :edit, :update, :destroy, :getcoordinates]
  before_action :check_user_track, only: [:show, :edit, :update, :getcoordinates]
  before_action :update_track_json, only: [:show, :getcoordinates]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.where(:user_id => current_user.id)
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /getcoordinates/1.json
  def getcoordinates
    render :json => @track.json_processed
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)
    @track.user_id = current_user.id

    if @track.valid?
      set_track_json
    end

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update    
    # @track.json_response = nil
    if @track.valid?
      set_track_json
    end

    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    if !is_user_track?
      @track.destroy
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title, :latitude_from, :longtitude_from, :latitude_to, :longtitude_to) #:user_id, :json_response, :json_processed
    end

    def is_user_track?
      @track.user_id != current_user.id
    end

    def check_user_track
      if is_user_track?
        redirect_to tracks_path
      end
    end

    def set_track_json
      requestUrl = "https://api.openrouteservice.org/directions?coordinates=#{@track.longtitude_from},#{@track.latitude_from}%7C#{@track.longtitude_to},#{@track.latitude_to}&profile=foot-hiking&preference=fastest&units=m&language=en&geometry=true&geometry_format=polyline&geometry_simplify=false&instructions=true&instructions_format=text&roundabout_exits=false&maneuvers=false&continue_straight=false&elevation=true&optimized=true&api_key={API_KEY}"
      @track.json_response = RestClient.get requestUrl

      parsed = JSON.parse(@track.json_response)
      @track.json_processed = parsed["routes"][0]["geometry"]
    end

    def update_track_json
      if @track.json_response.nil? || @track.json_response.empty? || @track.json_processed.nil? || @track.json_processed.empty?
        set_track_json
        @track.save
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HowMuchFurther</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      Logged in as: <i><%= current_user.email %></i> 
      <% if current_user.admin %>
        | <%= link_to "Admin", rails_admin_path %>
      <% end %>
      | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :publishdate %>
    <%= form.datetime_select :publishdate, id: :post_publishdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Publishdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.publishdate %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Publishdate:</strong>
  <%= @post.publishdate %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :track_user_id %>
  </div> -->

  <div style="margin-bottom: 20px;">
    <b>OpenRouteService link:</b> 
    <input type="text" id="urlInput" name="urlInput">
    <button type='button' onclick='app.parseurl()'>Parse</button>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :track_title %>
  </div>

  <div class="field">
    <%= form.label :latitude_from %>
    <%= form.text_field :latitude_from, id: :track_latitude_from %>
  </div>

  <div class="field">
    <%= form.label :longtitude_from %>
    <%= form.text_field :longtitude_from, id: :track_longtitude_from %>
  </div>

  <div class="field">
    <%= form.label :latitude_to %>
    <%= form.text_field :latitude_to, id: :track_latitude_to %>
  </div>

  <div class="field">
    <%= form.label :longtitude_to %>
    <%= form.text_field :longtitude_to, id: :track_longtitude_to %>
  </div>

  <%# <div class="field"> %>
    <%# <%= form.label :json_response %>
    <%# <%= form.text_field :json_response, id: :track_json_response %>
  <%# </div> %>

  <%# <div class="field"> %>
    <%# <%= form.label :json_processed %>
    <%# <%= form.text_field :json_processed, id: :track_json_processed %>
  <%# </div> %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <!-- <th>User</th> -->
      <th>Title</th>
      <th>Latitude from</th>
      <th>Longtitude from</th>
      <th>Latitude to</th>
      <th>Longtitude to</th>
      <!-- <th>Json response</th>
      <th>Json processed</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <!-- <td><%= track.user %></td> -->
        <td><%= track.title %></td>
        <td><%= track.latitude_from %></td>
        <td><%= track.longtitude_from %></td>
        <td><%= track.latitude_to %></td>
        <td><%= track.longtitude_to %></td>
        <!-- <td><%= track.json_response %></td>
        <td><%= track.json_processed %></td> -->
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p id="trackId" style="display: none;">
  <%= @track.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @track.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Latitude from:</strong>
  <%= @track.latitude_from %>
</p>

<p>
  <strong>Longtitude from:</strong>
  <%= @track.longtitude_from %>
</p>

<p>
  <strong>Latitude to:</strong>
  <%= @track.latitude_to %>
</p>

<p>
  <strong>Longtitude to:</strong>
  <%= @track.longtitude_to %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>

<canvas id="line-chart"></canvas>

<%# <%= raw @track.json_processed %>

<script>
  $(function() {
    $(".hmf-json").hide();

    var trackId = $("p#trackId").text();
    $.get("/tracks/getcoordinates/" + trackId).done(app.generateChart);
  });
</script>